
language: en
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- intent_split_symbol: +
  intent_tokenization_flag: true
  name: DIETClassifier
policies:
- name: FallbackPolicy
  nlu_threshold: 0.75
- name: AugmentedMemoizationPolicy
- name: FormPolicy
- name: MappingPolicy
- name: TEDPolicy
  epochs: 200
